file_format: "1"
id: flounderV2
name: flounderV2
type: shield
url: https://github.com/manofthebees/flounderV2-zmk
requires: [nice_nano_v2]
features:
  -keys
siblings:
  - flounderV2_left
  - flounderV2_right